# revision 33736
# category Package
# catalog-ctan /indexing/makeindex
# catalog-date 2011-09-24 09:40:13 +0200
# catalog-license other-free
# catalog-version 2.12
Name:		texlive-makeindex
Version:	2.12
Release:	15
Summary:	Process index output to produce typesettable code
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/indexing/makeindex
License:	OTHER-FREE
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/makeindex.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/makeindex.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea
Requires:	texlive-makeindex.bin

%description
A general purpose hierarchical index generator; it accepts one
or more input files (often produced by a text formatter such as
TeX or troff), sorts the entries, and produces an output file
which can be formatted. The formats of the input and output
files are specified in a style file; by default, input is
assumed to be an .idx file, as generated by LaTeX.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/makeindex/base/din.ist
%{_texmfdistdir}/makeindex/base/icase.ist
%{_texmfdistdir}/makeindex/base/latex.ist
%{_texmfdistdir}/makeindex/base/math.ist
%{_texmfdistdir}/makeindex/base/mkind.ist
%{_texmfdistdir}/makeindex/base/puncts.ist
%{_texmfdistdir}/makeindex/base/tex.ist
%{_texmfdistdir}/tex/plain/makeindex/idxmac.tex
%doc %{_mandir}/man1/makeindex.1*
%doc %{_texmfdistdir}/doc/man/man1/makeindex.man1.pdf
%doc %{_mandir}/man1/mkindex.1*
%doc %{_texmfdistdir}/doc/man/man1/mkindex.man1.pdf
%doc %{_texmfdistdir}/doc/support/makeindex/doc-src.zip
%doc %{_texmfdistdir}/doc/support/makeindex/ind-src.zip
%doc %{_texmfdistdir}/doc/support/makeindex/ind.pdf
%doc %{_texmfdistdir}/doc/support/makeindex/makeindex.pdf

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_datadir}
cp -fpar texmf-dist %{buildroot}%{_datadir}
mkdir -p %{buildroot}%{_mandir}/man1
mv %{buildroot}%{_texmfdistdir}/doc/man/man1/*.1 %{buildroot}%{_mandir}/man1
