# revision 23089
# category Package
# catalog-ctan /indexing/makeindex
# catalog-date 2011-01-01 19:05:40 +0100
# catalog-license other-free
# catalog-version 2.12
Name:		texlive-makeindex
Version:	2.12
Release:	1
Summary:	Process index output to produce typesettable code
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/indexing/makeindex
License:	OTHER-FREE
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/makeindex.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/makeindex.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(post):	texlive-tlpkg
Requires:	texlive-makeindex.bin
Conflicts:	texlive-texmf <= 20110705-3
Conflicts:	texlive-doc <= 20110705-3

%description
A general purpose hierarchical index generator; it accepts one
or more input files (often produced by a text formatter such as
TeX or troff), sorts the entries, and produces an output file
which can be formatted. The formats of the input and output
files are specified in a style file; by default, input is
assumed to be an .idx file, as generated by LaTeX.

%pre
    %_texmf_mktexlsr_pre

%post
    %_texmf_mktexlsr_post

%preun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_pre
    fi

%postun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/makeindex/base/din.ist
%{_texmfdistdir}/makeindex/base/icase.ist
%{_texmfdistdir}/makeindex/base/latex.ist
%{_texmfdistdir}/makeindex/base/math.ist
%{_texmfdistdir}/makeindex/base/mkind.ist
%{_texmfdistdir}/makeindex/base/puncts.ist
%{_texmfdistdir}/makeindex/base/tex.ist
%doc %{_texmfdistdir}/doc/support/makeindex/doc-src.zip
%doc %{_texmfdistdir}/doc/support/makeindex/ind-src.zip
%doc %{_texmfdistdir}/doc/support/makeindex/ind.pdf
%doc %{_texmfdistdir}/doc/support/makeindex/makeindex.pdf
%doc %{_mandir}/man1/makeindex.1*
%doc %{_texmfdir}/doc/man/man1/makeindex.man1.pdf
%doc %{_mandir}/man1/mkindex.1*
%doc %{_texmfdir}/doc/man/man1/mkindex.man1.pdf
%doc %{_tlpkgobjdir}/*.tlpobj

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_datadir}
cp -fpar texmf texmf-dist %{buildroot}%{_datadir}
mkdir -p %{buildroot}%{_mandir}/man1
mv %{buildroot}%{_texmfdir}/doc/man/man1/*.1 %{buildroot}%{_mandir}/man1
mkdir -p %{buildroot}%{_tlpkgobjdir}
cp -fpa tlpkg/tlpobj/*.tlpobj %{buildroot}%{_tlpkgobjdir}
