Name:		texlive-makeindex
Version:	62517
Release:	2
Summary:	Process index output to produce typesettable code
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/indexing/makeindex
License:	OTHER-FREE
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/makeindex.r%{version}.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/makeindex.doc.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea
Requires:	texlive-makeindex.bin

%description
A general purpose hierarchical index generator; it accepts one
or more input files (often produced by a text formatter such as
TeX or troff), sorts the entries, and produces an output file
which can be formatted. The formats of the input and output
files are specified in a style file; by default, input is
assumed to be an .idx file, as generated by LaTeX.

%post
%{_sbindir}/texlive.post

%postun
if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/makeindex
%{_texmfdistdir}/tex/plain/makeindex
%doc %{_mandir}/man1/*.1*
%doc %{_texmfdistdir}/doc/man/man1/*
%doc %{_texmfdistdir}/doc/support/makeindex

#-----------------------------------------------------------------------
%prep
%autosetup -p1 -c -a1

%build

%install
mkdir -p %{buildroot}%{_datadir}
cp -fpar texmf-dist %{buildroot}%{_datadir}
mkdir -p %{buildroot}%{_mandir}/man1
mv %{buildroot}%{_texmfdistdir}/doc/man/man1/*.1 %{buildroot}%{_mandir}/man1
